package com.jaroso.proyectosensores.entities;

public enum TipoSensor {
    BOMBA, ELECTROVALVULA, PRESION, CAUDAL, HUMEDAD, CONDUCTIVIDAD, EV_NUTRIENTES, VIENTO, DIR_VIENTO, PLUVIOMETRIA, TEMPERATURA, HUMEDAD_EXTERNA, PRESION_EXTERNA, NIVEL
}